//
// Created by rfleuryleveso on 20/04/23.
//

#ifndef _IDT_H_
#define _IDT_H_
#include <stdint.h>
#include "../memory/memory_tools.h"

// Interrupt table structure
typedef struct {
	uint16_t offset_low;  // 16 bits of the interrupt handler address
	uint16_t selector;    // code segment selector
	uint8_t  ist;         // interrupt stack table index
	uint8_t  type_attr;   // interrupt gate type and attributes
	uint16_t offset_mid;  // 16 middle bits of the interrupt handler address
	uint32_t offset_high; // 32 higher bits of the interrupt handler address
	uint32_t zero;        // always set to 0
} __attribute__((packed)) __attribute__((aligned(0x10)))  idt_entry_t;

// Interrupt table pointer structure
typedef struct {
	uint16_t size;      // table size -1
	uint64_t base;       // table address
} __attribute__((packed)) __attribute__((aligned(0x10)))  idt_ptr_t;
extern void isr_handler_0(void);
extern void isr_handler_1(void);
extern void isr_handler_2(void);
extern void isr_handler_3(void);
extern void isr_handler_4(void);
extern void isr_handler_5(void);
extern void isr_handler_6(void);
extern void isr_handler_7(void);
extern void isr_handler_8(void);
extern void isr_handler_9(void);
extern void isr_handler_10(void);
extern void isr_handler_11(void);
extern void isr_handler_12(void);
extern void isr_handler_13(void);
extern void isr_handler_14(void);
extern void isr_handler_15(void);
extern void isr_handler_16(void);
extern void isr_handler_17(void);
extern void isr_handler_18(void);
extern void isr_handler_19(void);
extern void isr_handler_20(void);
extern void isr_handler_21(void);
extern void isr_handler_22(void);
extern void isr_handler_23(void);
extern void isr_handler_24(void);
extern void isr_handler_25(void);
extern void isr_handler_26(void);
extern void isr_handler_27(void);
extern void isr_handler_28(void);
extern void isr_handler_29(void);
extern void isr_handler_30(void);
extern void isr_handler_31(void);
extern void isr_handler_32(void);
extern void isr_handler_33(void);
extern void isr_handler_34(void);
extern void isr_handler_35(void);
extern void isr_handler_36(void);
extern void isr_handler_37(void);
extern void isr_handler_38(void);
extern void isr_handler_39(void);
extern void isr_handler_40(void);
extern void isr_handler_41(void);
extern void isr_handler_42(void);
extern void isr_handler_43(void);
extern void isr_handler_44(void);
extern void isr_handler_45(void);
extern void isr_handler_46(void);
extern void isr_handler_47(void);
extern void isr_handler_48(void);
extern void isr_handler_49(void);
extern void isr_handler_50(void);
extern void isr_handler_51(void);
extern void isr_handler_52(void);
extern void isr_handler_53(void);
extern void isr_handler_54(void);
extern void isr_handler_55(void);
extern void isr_handler_56(void);
extern void isr_handler_57(void);
extern void isr_handler_58(void);
extern void isr_handler_59(void);
extern void isr_handler_60(void);
extern void isr_handler_61(void);
extern void isr_handler_62(void);
extern void isr_handler_63(void);
extern void isr_handler_64(void);
extern void isr_handler_65(void);
extern void isr_handler_66(void);
extern void isr_handler_67(void);
extern void isr_handler_68(void);
extern void isr_handler_69(void);
extern void isr_handler_70(void);
extern void isr_handler_71(void);
extern void isr_handler_72(void);
extern void isr_handler_73(void);
extern void isr_handler_74(void);
extern void isr_handler_75(void);
extern void isr_handler_76(void);
extern void isr_handler_77(void);
extern void isr_handler_78(void);
extern void isr_handler_79(void);
extern void isr_handler_80(void);
extern void isr_handler_81(void);
extern void isr_handler_82(void);
extern void isr_handler_83(void);
extern void isr_handler_84(void);
extern void isr_handler_85(void);
extern void isr_handler_86(void);
extern void isr_handler_87(void);
extern void isr_handler_88(void);
extern void isr_handler_89(void);
extern void isr_handler_90(void);
extern void isr_handler_91(void);
extern void isr_handler_92(void);
extern void isr_handler_93(void);
extern void isr_handler_94(void);
extern void isr_handler_95(void);
extern void isr_handler_96(void);
extern void isr_handler_97(void);
extern void isr_handler_98(void);
extern void isr_handler_99(void);
extern void isr_handler_100(void);
extern void isr_handler_101(void);
extern void isr_handler_102(void);
extern void isr_handler_103(void);
extern void isr_handler_104(void);
extern void isr_handler_105(void);
extern void isr_handler_106(void);
extern void isr_handler_107(void);
extern void isr_handler_108(void);
extern void isr_handler_109(void);
extern void isr_handler_110(void);
extern void isr_handler_111(void);
extern void isr_handler_112(void);
extern void isr_handler_113(void);
extern void isr_handler_114(void);
extern void isr_handler_115(void);
extern void isr_handler_116(void);
extern void isr_handler_117(void);
extern void isr_handler_118(void);
extern void isr_handler_119(void);
extern void isr_handler_120(void);
extern void isr_handler_121(void);
extern void isr_handler_122(void);
extern void isr_handler_123(void);
extern void isr_handler_124(void);
extern void isr_handler_125(void);
extern void isr_handler_126(void);
extern void isr_handler_127(void);
extern void isr_handler_128(void);
extern void isr_handler_129(void);
extern void isr_handler_130(void);
extern void isr_handler_131(void);
extern void isr_handler_132(void);
extern void isr_handler_133(void);
extern void isr_handler_134(void);
extern void isr_handler_135(void);
extern void isr_handler_136(void);
extern void isr_handler_137(void);
extern void isr_handler_138(void);
extern void isr_handler_139(void);
extern void isr_handler_140(void);
extern void isr_handler_141(void);
extern void isr_handler_142(void);
extern void isr_handler_143(void);
extern void isr_handler_144(void);
extern void isr_handler_145(void);
extern void isr_handler_146(void);
extern void isr_handler_147(void);
extern void isr_handler_148(void);
extern void isr_handler_149(void);
extern void isr_handler_150(void);
extern void isr_handler_151(void);
extern void isr_handler_152(void);
extern void isr_handler_153(void);
extern void isr_handler_154(void);
extern void isr_handler_155(void);
extern void isr_handler_156(void);
extern void isr_handler_157(void);
extern void isr_handler_158(void);
extern void isr_handler_159(void);
extern void isr_handler_160(void);
extern void isr_handler_161(void);
extern void isr_handler_162(void);
extern void isr_handler_163(void);
extern void isr_handler_164(void);
extern void isr_handler_165(void);
extern void isr_handler_166(void);
extern void isr_handler_167(void);
extern void isr_handler_168(void);
extern void isr_handler_169(void);
extern void isr_handler_170(void);
extern void isr_handler_171(void);
extern void isr_handler_172(void);
extern void isr_handler_173(void);
extern void isr_handler_174(void);
extern void isr_handler_175(void);
extern void isr_handler_176(void);
extern void isr_handler_177(void);
extern void isr_handler_178(void);
extern void isr_handler_179(void);
extern void isr_handler_180(void);
extern void isr_handler_181(void);
extern void isr_handler_182(void);
extern void isr_handler_183(void);
extern void isr_handler_184(void);
extern void isr_handler_185(void);
extern void isr_handler_186(void);
extern void isr_handler_187(void);
extern void isr_handler_188(void);
extern void isr_handler_189(void);
extern void isr_handler_190(void);
extern void isr_handler_191(void);
extern void isr_handler_192(void);
extern void isr_handler_193(void);
extern void isr_handler_194(void);
extern void isr_handler_195(void);
extern void isr_handler_196(void);
extern void isr_handler_197(void);
extern void isr_handler_198(void);
extern void isr_handler_199(void);
extern void isr_handler_200(void);
extern void isr_handler_201(void);
extern void isr_handler_202(void);
extern void isr_handler_203(void);
extern void isr_handler_204(void);
extern void isr_handler_205(void);
extern void isr_handler_206(void);
extern void isr_handler_207(void);
extern void isr_handler_208(void);
extern void isr_handler_209(void);
extern void isr_handler_210(void);
extern void isr_handler_211(void);
extern void isr_handler_212(void);
extern void isr_handler_213(void);
extern void isr_handler_214(void);
extern void isr_handler_215(void);
extern void isr_handler_216(void);
extern void isr_handler_217(void);
extern void isr_handler_218(void);
extern void isr_handler_219(void);
extern void isr_handler_220(void);
extern void isr_handler_221(void);
extern void isr_handler_222(void);
extern void isr_handler_223(void);
extern void isr_handler_224(void);
extern void isr_handler_225(void);
extern void isr_handler_226(void);
extern void isr_handler_227(void);
extern void isr_handler_228(void);
extern void isr_handler_229(void);
extern void isr_handler_230(void);
extern void isr_handler_231(void);
extern void isr_handler_232(void);
extern void isr_handler_233(void);
extern void isr_handler_234(void);
extern void isr_handler_235(void);
extern void isr_handler_236(void);
extern void isr_handler_237(void);
extern void isr_handler_238(void);
extern void isr_handler_239(void);
extern void isr_handler_240(void);
extern void isr_handler_241(void);
extern void isr_handler_242(void);
extern void isr_handler_243(void);
extern void isr_handler_244(void);
extern void isr_handler_245(void);
extern void isr_handler_246(void);
extern void isr_handler_247(void);
extern void isr_handler_248(void);
extern void isr_handler_249(void);
extern void isr_handler_250(void);
extern void isr_handler_251(void);
extern void isr_handler_252(void);
extern void isr_handler_253(void);
extern void isr_handler_254(void);
extern void isr_handler_255(void);
void __attribute__((optimize("O0"))) interrupt_handler_0 ();
void __attribute__((optimize("O0"))) interrupt_handler_1 ();
void __attribute__((optimize("O0"))) interrupt_handler_2 ();
void __attribute__((optimize("O0"))) interrupt_handler_3 ();
void __attribute__((optimize("O0"))) interrupt_handler_4 ();
void __attribute__((optimize("O0"))) interrupt_handler_5 ();
void __attribute__((optimize("O0"))) interrupt_handler_6 ();
void __attribute__((optimize("O0"))) interrupt_handler_7 ();
void __attribute__((optimize("O0"))) interrupt_handler_8 ();
void __attribute__((optimize("O0"))) interrupt_handler_9 ();
void __attribute__((optimize("O0"))) interrupt_handler_10 ();
void __attribute__((optimize("O0"))) interrupt_handler_11 ();
void __attribute__((optimize("O0"))) interrupt_handler_12 ();
void __attribute__((optimize("O0"))) interrupt_handler_13 ();
void __attribute__((optimize("O0"))) interrupt_handler_14 ();
void __attribute__((optimize("O0"))) interrupt_handler_15 ();
void __attribute__((optimize("O0"))) interrupt_handler_16 ();
void __attribute__((optimize("O0"))) interrupt_handler_17 ();
void __attribute__((optimize("O0"))) interrupt_handler_18 ();
void __attribute__((optimize("O0"))) interrupt_handler_19 ();
void __attribute__((optimize("O0"))) interrupt_handler_20 ();
void __attribute__((optimize("O0"))) interrupt_handler_21 ();
void __attribute__((optimize("O0"))) interrupt_handler_22 ();
void __attribute__((optimize("O0"))) interrupt_handler_23 ();
void __attribute__((optimize("O0"))) interrupt_handler_24 ();
void __attribute__((optimize("O0"))) interrupt_handler_25 ();
void __attribute__((optimize("O0"))) interrupt_handler_26 ();
void __attribute__((optimize("O0"))) interrupt_handler_27 ();
void __attribute__((optimize("O0"))) interrupt_handler_28 ();
void __attribute__((optimize("O0"))) interrupt_handler_29 ();
void __attribute__((optimize("O0"))) interrupt_handler_30 ();
void __attribute__((optimize("O0"))) interrupt_handler_31 ();
void __attribute__((optimize("O0"))) interrupt_handler_32 ();
void __attribute__((optimize("O0"))) interrupt_handler_33 ();
void __attribute__((optimize("O0"))) interrupt_handler_34 ();
void __attribute__((optimize("O0"))) interrupt_handler_35 ();
void __attribute__((optimize("O0"))) interrupt_handler_36 ();
void __attribute__((optimize("O0"))) interrupt_handler_37 ();
void __attribute__((optimize("O0"))) interrupt_handler_38 ();
void __attribute__((optimize("O0"))) interrupt_handler_39 ();
void __attribute__((optimize("O0"))) interrupt_handler_40 ();
void __attribute__((optimize("O0"))) interrupt_handler_41 ();
void __attribute__((optimize("O0"))) interrupt_handler_42 ();
void __attribute__((optimize("O0"))) interrupt_handler_43 ();
void __attribute__((optimize("O0"))) interrupt_handler_44 ();
void __attribute__((optimize("O0"))) interrupt_handler_45 ();
void __attribute__((optimize("O0"))) interrupt_handler_46 ();
void __attribute__((optimize("O0"))) interrupt_handler_47 ();
void __attribute__((optimize("O0"))) interrupt_handler_48 ();
void __attribute__((optimize("O0"))) interrupt_handler_49 ();
void __attribute__((optimize("O0"))) interrupt_handler_50 ();
void __attribute__((optimize("O0"))) interrupt_handler_51 ();
void __attribute__((optimize("O0"))) interrupt_handler_52 ();
void __attribute__((optimize("O0"))) interrupt_handler_53 ();
void __attribute__((optimize("O0"))) interrupt_handler_54 ();
void __attribute__((optimize("O0"))) interrupt_handler_55 ();
void __attribute__((optimize("O0"))) interrupt_handler_56 ();
void __attribute__((optimize("O0"))) interrupt_handler_57 ();
void __attribute__((optimize("O0"))) interrupt_handler_58 ();
void __attribute__((optimize("O0"))) interrupt_handler_59 ();
void __attribute__((optimize("O0"))) interrupt_handler_60 ();
void __attribute__((optimize("O0"))) interrupt_handler_61 ();
void __attribute__((optimize("O0"))) interrupt_handler_62 ();
void __attribute__((optimize("O0"))) interrupt_handler_63 ();
void __attribute__((optimize("O0"))) interrupt_handler_64 ();
void __attribute__((optimize("O0"))) interrupt_handler_65 ();
void __attribute__((optimize("O0"))) interrupt_handler_66 ();
void __attribute__((optimize("O0"))) interrupt_handler_67 ();
void __attribute__((optimize("O0"))) interrupt_handler_68 ();
void __attribute__((optimize("O0"))) interrupt_handler_69 ();
void __attribute__((optimize("O0"))) interrupt_handler_70 ();
void __attribute__((optimize("O0"))) interrupt_handler_71 ();
void __attribute__((optimize("O0"))) interrupt_handler_72 ();
void __attribute__((optimize("O0"))) interrupt_handler_73 ();
void __attribute__((optimize("O0"))) interrupt_handler_74 ();
void __attribute__((optimize("O0"))) interrupt_handler_75 ();
void __attribute__((optimize("O0"))) interrupt_handler_76 ();
void __attribute__((optimize("O0"))) interrupt_handler_77 ();
void __attribute__((optimize("O0"))) interrupt_handler_78 ();
void __attribute__((optimize("O0"))) interrupt_handler_79 ();
void __attribute__((optimize("O0"))) interrupt_handler_80 ();
void __attribute__((optimize("O0"))) interrupt_handler_81 ();
void __attribute__((optimize("O0"))) interrupt_handler_82 ();
void __attribute__((optimize("O0"))) interrupt_handler_83 ();
void __attribute__((optimize("O0"))) interrupt_handler_84 ();
void __attribute__((optimize("O0"))) interrupt_handler_85 ();
void __attribute__((optimize("O0"))) interrupt_handler_86 ();
void __attribute__((optimize("O0"))) interrupt_handler_87 ();
void __attribute__((optimize("O0"))) interrupt_handler_88 ();
void __attribute__((optimize("O0"))) interrupt_handler_89 ();
void __attribute__((optimize("O0"))) interrupt_handler_90 ();
void __attribute__((optimize("O0"))) interrupt_handler_91 ();
void __attribute__((optimize("O0"))) interrupt_handler_92 ();
void __attribute__((optimize("O0"))) interrupt_handler_93 ();
void __attribute__((optimize("O0"))) interrupt_handler_94 ();
void __attribute__((optimize("O0"))) interrupt_handler_95 ();
void __attribute__((optimize("O0"))) interrupt_handler_96 ();
void __attribute__((optimize("O0"))) interrupt_handler_97 ();
void __attribute__((optimize("O0"))) interrupt_handler_98 ();
void __attribute__((optimize("O0"))) interrupt_handler_99 ();
void __attribute__((optimize("O0"))) interrupt_handler_100 ();
void __attribute__((optimize("O0"))) interrupt_handler_101 ();
void __attribute__((optimize("O0"))) interrupt_handler_102 ();
void __attribute__((optimize("O0"))) interrupt_handler_103 ();
void __attribute__((optimize("O0"))) interrupt_handler_104 ();
void __attribute__((optimize("O0"))) interrupt_handler_105 ();
void __attribute__((optimize("O0"))) interrupt_handler_106 ();
void __attribute__((optimize("O0"))) interrupt_handler_107 ();
void __attribute__((optimize("O0"))) interrupt_handler_108 ();
void __attribute__((optimize("O0"))) interrupt_handler_109 ();
void __attribute__((optimize("O0"))) interrupt_handler_110 ();
void __attribute__((optimize("O0"))) interrupt_handler_111 ();
void __attribute__((optimize("O0"))) interrupt_handler_112 ();
void __attribute__((optimize("O0"))) interrupt_handler_113 ();
void __attribute__((optimize("O0"))) interrupt_handler_114 ();
void __attribute__((optimize("O0"))) interrupt_handler_115 ();
void __attribute__((optimize("O0"))) interrupt_handler_116 ();
void __attribute__((optimize("O0"))) interrupt_handler_117 ();
void __attribute__((optimize("O0"))) interrupt_handler_118 ();
void __attribute__((optimize("O0"))) interrupt_handler_119 ();
void __attribute__((optimize("O0"))) interrupt_handler_120 ();
void __attribute__((optimize("O0"))) interrupt_handler_121 ();
void __attribute__((optimize("O0"))) interrupt_handler_122 ();
void __attribute__((optimize("O0"))) interrupt_handler_123 ();
void __attribute__((optimize("O0"))) interrupt_handler_124 ();
void __attribute__((optimize("O0"))) interrupt_handler_125 ();
void __attribute__((optimize("O0"))) interrupt_handler_126 ();
void __attribute__((optimize("O0"))) interrupt_handler_127 ();
void __attribute__((optimize("O0"))) interrupt_handler_128 ();
void __attribute__((optimize("O0"))) interrupt_handler_129 ();
void __attribute__((optimize("O0"))) interrupt_handler_130 ();
void __attribute__((optimize("O0"))) interrupt_handler_131 ();
void __attribute__((optimize("O0"))) interrupt_handler_132 ();
void __attribute__((optimize("O0"))) interrupt_handler_133 ();
void __attribute__((optimize("O0"))) interrupt_handler_134 ();
void __attribute__((optimize("O0"))) interrupt_handler_135 ();
void __attribute__((optimize("O0"))) interrupt_handler_136 ();
void __attribute__((optimize("O0"))) interrupt_handler_137 ();
void __attribute__((optimize("O0"))) interrupt_handler_138 ();
void __attribute__((optimize("O0"))) interrupt_handler_139 ();
void __attribute__((optimize("O0"))) interrupt_handler_140 ();
void __attribute__((optimize("O0"))) interrupt_handler_141 ();
void __attribute__((optimize("O0"))) interrupt_handler_142 ();
void __attribute__((optimize("O0"))) interrupt_handler_143 ();
void __attribute__((optimize("O0"))) interrupt_handler_144 ();
void __attribute__((optimize("O0"))) interrupt_handler_145 ();
void __attribute__((optimize("O0"))) interrupt_handler_146 ();
void __attribute__((optimize("O0"))) interrupt_handler_147 ();
void __attribute__((optimize("O0"))) interrupt_handler_148 ();
void __attribute__((optimize("O0"))) interrupt_handler_149 ();
void __attribute__((optimize("O0"))) interrupt_handler_150 ();
void __attribute__((optimize("O0"))) interrupt_handler_151 ();
void __attribute__((optimize("O0"))) interrupt_handler_152 ();
void __attribute__((optimize("O0"))) interrupt_handler_153 ();
void __attribute__((optimize("O0"))) interrupt_handler_154 ();
void __attribute__((optimize("O0"))) interrupt_handler_155 ();
void __attribute__((optimize("O0"))) interrupt_handler_156 ();
void __attribute__((optimize("O0"))) interrupt_handler_157 ();
void __attribute__((optimize("O0"))) interrupt_handler_158 ();
void __attribute__((optimize("O0"))) interrupt_handler_159 ();
void __attribute__((optimize("O0"))) interrupt_handler_160 ();
void __attribute__((optimize("O0"))) interrupt_handler_161 ();
void __attribute__((optimize("O0"))) interrupt_handler_162 ();
void __attribute__((optimize("O0"))) interrupt_handler_163 ();
void __attribute__((optimize("O0"))) interrupt_handler_164 ();
void __attribute__((optimize("O0"))) interrupt_handler_165 ();
void __attribute__((optimize("O0"))) interrupt_handler_166 ();
void __attribute__((optimize("O0"))) interrupt_handler_167 ();
void __attribute__((optimize("O0"))) interrupt_handler_168 ();
void __attribute__((optimize("O0"))) interrupt_handler_169 ();
void __attribute__((optimize("O0"))) interrupt_handler_170 ();
void __attribute__((optimize("O0"))) interrupt_handler_171 ();
void __attribute__((optimize("O0"))) interrupt_handler_172 ();
void __attribute__((optimize("O0"))) interrupt_handler_173 ();
void __attribute__((optimize("O0"))) interrupt_handler_174 ();
void __attribute__((optimize("O0"))) interrupt_handler_175 ();
void __attribute__((optimize("O0"))) interrupt_handler_176 ();
void __attribute__((optimize("O0"))) interrupt_handler_177 ();
void __attribute__((optimize("O0"))) interrupt_handler_178 ();
void __attribute__((optimize("O0"))) interrupt_handler_179 ();
void __attribute__((optimize("O0"))) interrupt_handler_180 ();
void __attribute__((optimize("O0"))) interrupt_handler_181 ();
void __attribute__((optimize("O0"))) interrupt_handler_182 ();
void __attribute__((optimize("O0"))) interrupt_handler_183 ();
void __attribute__((optimize("O0"))) interrupt_handler_184 ();
void __attribute__((optimize("O0"))) interrupt_handler_185 ();
void __attribute__((optimize("O0"))) interrupt_handler_186 ();
void __attribute__((optimize("O0"))) interrupt_handler_187 ();
void __attribute__((optimize("O0"))) interrupt_handler_188 ();
void __attribute__((optimize("O0"))) interrupt_handler_189 ();
void __attribute__((optimize("O0"))) interrupt_handler_190 ();
void __attribute__((optimize("O0"))) interrupt_handler_191 ();
void __attribute__((optimize("O0"))) interrupt_handler_192 ();
void __attribute__((optimize("O0"))) interrupt_handler_193 ();
void __attribute__((optimize("O0"))) interrupt_handler_194 ();
void __attribute__((optimize("O0"))) interrupt_handler_195 ();
void __attribute__((optimize("O0"))) interrupt_handler_196 ();
void __attribute__((optimize("O0"))) interrupt_handler_197 ();
void __attribute__((optimize("O0"))) interrupt_handler_198 ();
void __attribute__((optimize("O0"))) interrupt_handler_199 ();
void __attribute__((optimize("O0"))) interrupt_handler_200 ();
void __attribute__((optimize("O0"))) interrupt_handler_201 ();
void __attribute__((optimize("O0"))) interrupt_handler_202 ();
void __attribute__((optimize("O0"))) interrupt_handler_203 ();
void __attribute__((optimize("O0"))) interrupt_handler_204 ();
void __attribute__((optimize("O0"))) interrupt_handler_205 ();
void __attribute__((optimize("O0"))) interrupt_handler_206 ();
void __attribute__((optimize("O0"))) interrupt_handler_207 ();
void __attribute__((optimize("O0"))) interrupt_handler_208 ();
void __attribute__((optimize("O0"))) interrupt_handler_209 ();
void __attribute__((optimize("O0"))) interrupt_handler_210 ();
void __attribute__((optimize("O0"))) interrupt_handler_211 ();
void __attribute__((optimize("O0"))) interrupt_handler_212 ();
void __attribute__((optimize("O0"))) interrupt_handler_213 ();
void __attribute__((optimize("O0"))) interrupt_handler_214 ();
void __attribute__((optimize("O0"))) interrupt_handler_215 ();
void __attribute__((optimize("O0"))) interrupt_handler_216 ();
void __attribute__((optimize("O0"))) interrupt_handler_217 ();
void __attribute__((optimize("O0"))) interrupt_handler_218 ();
void __attribute__((optimize("O0"))) interrupt_handler_219 ();
void __attribute__((optimize("O0"))) interrupt_handler_220 ();
void __attribute__((optimize("O0"))) interrupt_handler_221 ();
void __attribute__((optimize("O0"))) interrupt_handler_222 ();
void __attribute__((optimize("O0"))) interrupt_handler_223 ();
void __attribute__((optimize("O0"))) interrupt_handler_224 ();
void __attribute__((optimize("O0"))) interrupt_handler_225 ();
void __attribute__((optimize("O0"))) interrupt_handler_226 ();
void __attribute__((optimize("O0"))) interrupt_handler_227 ();
void __attribute__((optimize("O0"))) interrupt_handler_228 ();
void __attribute__((optimize("O0"))) interrupt_handler_229 ();
void __attribute__((optimize("O0"))) interrupt_handler_230 ();
void __attribute__((optimize("O0"))) interrupt_handler_231 ();
void __attribute__((optimize("O0"))) interrupt_handler_232 ();
void __attribute__((optimize("O0"))) interrupt_handler_233 ();
void __attribute__((optimize("O0"))) interrupt_handler_234 ();
void __attribute__((optimize("O0"))) interrupt_handler_235 ();
void __attribute__((optimize("O0"))) interrupt_handler_236 ();
void __attribute__((optimize("O0"))) interrupt_handler_237 ();
void __attribute__((optimize("O0"))) interrupt_handler_238 ();
void __attribute__((optimize("O0"))) interrupt_handler_239 ();
void __attribute__((optimize("O0"))) interrupt_handler_240 ();
void __attribute__((optimize("O0"))) interrupt_handler_241 ();
void __attribute__((optimize("O0"))) interrupt_handler_242 ();
void __attribute__((optimize("O0"))) interrupt_handler_243 ();
void __attribute__((optimize("O0"))) interrupt_handler_244 ();
void __attribute__((optimize("O0"))) interrupt_handler_245 ();
void __attribute__((optimize("O0"))) interrupt_handler_246 ();
void __attribute__((optimize("O0"))) interrupt_handler_247 ();
void __attribute__((optimize("O0"))) interrupt_handler_248 ();
void __attribute__((optimize("O0"))) interrupt_handler_249 ();
void __attribute__((optimize("O0"))) interrupt_handler_250 ();
void __attribute__((optimize("O0"))) interrupt_handler_251 ();
void __attribute__((optimize("O0"))) interrupt_handler_252 ();
void __attribute__((optimize("O0"))) interrupt_handler_253 ();
void __attribute__((optimize("O0"))) interrupt_handler_254 ();
void __attribute__((optimize("O0"))) interrupt_handler_255 ();

__attribute__((aligned(0x10)))
extern idt_entry_t idt_entries[256];
extern volatile uint64_t last_called_isr;

void init_idt();

#endif //_IDT_H_